export const TITLE = "오진수"
export const DESCRIPTION = "생산성을 중시하는 풀스택 개발자입니다."
export const AUTHOR="오진수"
export const AGILE_SOFTWARE = "애자일 소프트웨어"
export const AGILE_SOFTWARE_DESCRIPTION="비즈니스의 성공을 주도하는 프로그래밍에 대해 생각해요."
export const STARTUP_JOURNEY = "스타트업 여행기"
export const STARTUP_JOURNEY_DESCRIPTION = "실전을 통해 성장하려고 해요."
export const ORIGIN="https://ohjinsu.me"